# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fbgraph_rails"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = "2012-12-18"
  s.description = "Support for sessions tied to Facebook users."
  s.email = "victor@costan.us"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".project",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/facebook_oauth_controller.rb",
    "app/helpers/facebook_oauth_helper.rb",
    "config/routes.rb",
    "fbgraph_rails.gemspec",
    "lib/fbgraph_rails.rb",
    "lib/fbgraph_rails/controller.rb",
    "lib/fbgraph_rails/engine.rb",
    "lib/fbgraph_rails/fbgraph_client.rb",
    "test/fbgraph_rails_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/costan/fbgraph_rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Rails plug-in integrating the fbgraph gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<erubis>, [">= 2.7.0"])
      s.add_runtime_dependency(%q<fbgraph>, [">= 1.10.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.7.5"])
      s.add_runtime_dependency(%q<oauth2>, [">= 0.8.0"])
      s.add_runtime_dependency(%q<rails>, [">= 3.2.9"])
      s.add_development_dependency(%q<bundler>, [">= 1.2.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_development_dependency(%q<sqlite3>, [">= 1.3.6"])
    else
      s.add_dependency(%q<erubis>, [">= 2.7.0"])
      s.add_dependency(%q<fbgraph>, [">= 1.10.0"])
      s.add_dependency(%q<json>, [">= 1.7.5"])
      s.add_dependency(%q<oauth2>, [">= 0.8.0"])
      s.add_dependency(%q<rails>, [">= 3.2.9"])
      s.add_dependency(%q<bundler>, [">= 1.2.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_dependency(%q<sqlite3>, [">= 1.3.6"])
    end
  else
    s.add_dependency(%q<erubis>, [">= 2.7.0"])
    s.add_dependency(%q<fbgraph>, [">= 1.10.0"])
    s.add_dependency(%q<json>, [">= 1.7.5"])
    s.add_dependency(%q<oauth2>, [">= 0.8.0"])
    s.add_dependency(%q<rails>, [">= 3.2.9"])
    s.add_dependency(%q<bundler>, [">= 1.2.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    s.add_dependency(%q<sqlite3>, [">= 1.3.6"])
  end
end

